## Day 11: ML Models

In [1]:
import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
df_wti = yf.download("CL=F", start="2000-01-01", end="2025-01-01", multi_level_index=False)
print("WTI Crude Oil Prices")
df_wti.head()

[*********************100%***********************]  1 of 1 completed

WTI Crude Oil Prices

                Close       High        Low       Open  Volume
Date
2000-08-23  32.049999  32.799999  31.950001  31.950001   79385
2000-08-24  31.629999  32.240002  31.400000  31.900000   72978
2000-08-25  32.049999  32.099998  31.320000  31.700001   44601
2000-08-28  32.869999  32.919998  31.860001  32.040001   46770
2000-08-29  32.720001  33.029999  32.560001  32.820000   49131

In [3]:
df_brent = yf.download("BZ=F", start="2000-01-01", end="2025-01-01", multi_level_index=False)
print("Brent Crude Oil Prices")
df_brent.head()

[*********************100%***********************]  1 of 1 completed

Brent Crude Oil Prices

                Close       High        Low       Open  Volume
Date
2007-07-30  75.739998  76.529999  75.440002  75.849998    2575
2007-07-31  77.050003  77.169998  75.669998  75.699997    3513
2007-08-01  75.349998  77.059998  74.860001  77.000000    3930
2007-08-02  75.760002  76.209999  74.269997  75.220001    6180
2007-08-03  74.750000  76.000000  74.529999  75.389999    4387

In [ ]:
# We want to add log returns to the data

df_wti["Log Returns"] = (np.log(df_wti["Close"] / df_wti["Close"].shift(1)))
df_brent["Log Returns"] = (np.log(df_brent["Close"] / df_brent["Close"].shift(1)))

df_wti = df_wti[1:]
df_brent = df_brent[1:]

print(df_wti['Log Returns'])
print("---------------------------------")
print(df_brent['Log Returns'])

Date
2000-08-24   -0.013191
2000-08-25    0.013191
2000-08-28    0.025263
2000-08-29   -0.004574
2000-08-30    0.020569
                ...
2024-12-24    0.012344
2024-12-26   -0.006871
2024-12-27    0.013978
2024-12-30    0.005509
2024-12-31    0.010231
Name: Log Returns, Length: 6114, dtype: float64
---------------------------------
Date
2007-07-31    0.017148
2007-08-01   -0.022311
2007-08-02    0.005427
2007-08-03   -0.013421
2007-08-06   -0.049078
                ...
2024-12-24    0.012995
2024-12-26   -0.004358
2024-12-27    0.012345
2024-12-30    0.002962
2024-12-31    0.003355
Name: Log Returns, Length: 4332, dtype: float64

In [10]:
def classify_returns(df):
    df['Class'] = np.where(df['Log Returns'] > 0, 1, 0)
    return df

In [11]:
classify_returns(df_wti)
classify_returns(df_brent)


print(df_wti.head())
print(df_brent.head())

                Close       High        Low       Open  Volume  Log Returns  \
Date
2000-08-24  31.629999  32.240002  31.400000  31.900000   72978    -0.013191
2000-08-25  32.049999  32.099998  31.320000  31.700001   44601     0.013191
2000-08-28  32.869999  32.919998  31.860001  32.040001   46770     0.025263
2000-08-29  32.720001  33.029999  32.560001  32.820000   49131    -0.004574
2000-08-30  33.400002  33.400002  32.099998  32.750000   79214     0.020569

            Class
Date
2000-08-24      0
2000-08-25      1
2000-08-28      1
2000-08-29      0
2000-08-30      1
                Close       High        Low       Open  Volume  Log Returns  \
Date
2007-07-31  77.050003  77.169998  75.669998  75.699997    3513     0.017148
2007-08-01  75.349998  77.059998  74.860001  77.000000    3930    -0.022311
2007-08-02  75.760002  76.209999  74.269997  75.220001    6180     0.005427
2007-08-03  74.750000  76.000000  74.529999  75.389999    4387    -0.013421
2007-08-06  71.169998  74.599998  70.870003  74.540001    7201    -0.049078

            Class
Date
2007-07-31      1
2007-08-01      0
2007-08-02      1
2007-08-03      0
2007-08-06      0

In [ ]:
df_brent['momentum_5_days'] = df_wti['Close'].rolling(window=5).mean()
df_wti['momentum_5_days'] = df_wti['Close'].rolling(window=5).mean()

df_brent['momentum_20_days'] = df_wti['Close'].rolling(window=20).mean()
df_wti['momentum_20_days'] = df_wti['Close'].rolling(window=20).mean()

df_brent['momentum_50_days'] = df_wti['Close'].rolling(window=50).mean()
df_wti['momentum_50_days'] = df_wti['Close'].rolling(window=50).mean()

Date
2000-08-30    32.534
2000-08-31    32.828
2000-09-01    33.094
2000-09-05    33.280
2000-09-06    33.726
Name: Close, dtype: float64

In [ ]:
df_brent['rolling_volatility_5_days'] = df_wti['Log Returns'].rolling(window=5).std()
df_wti['rolling_volatility_5_days'] = df_wti['Log Returns'].rolling(window=5).std()

df_brent['rolling_volatility_20_days'] = df_wti['Log Returns'].rolling(window=20).std()
df_wti['rolling_volatility_20_days'] = df_wti['Log Returns'].rolling(window=20).std()

df_brent['rolling_volatility_50_days'] = df_wti['Log Returns'].rolling(window=50).std()
df_wti['rolling_volatility_50_days'] = df_wti['Log Returns'].rolling(window=50).std()

In [ ]:
df_brent